Modify configure script to download and verify msgpack and rapidjson files

diff --git a/build/configure b/build/configure
--- a/build/configure
+++ b/build/configure
@@ -53,16 +53,27 @@ if [ ! -e /usr/include/boost148 ]; then
 fi
 
 if [ ! -e ${root_dir}/rapidjson-1.0.2.tar.gz ]; then
-    echo "rapidjson 1.0.2 tar file (${root_dir}/v1.0.2.tar.gz) is missing" >& 2
-    echo "Download it from here: https://github.com/miloyip/rapidjson/archive/v1.0.2.tar.gz" >& 2
+    echo "rapidjson 1.0.2 tar file (${root_dir}/v1.0.2.tar.gz) is missing. Downloading..." >& 2
+    wget -O ${root_dir}/rapidjson-1.0.2.tar.gz https://github.com/miloyip/rapidjson/archive/v1.0.2.tar.gz >& 2
+fi
+
+echo "c3711ed2b3c76a5565ee9f0128bb4ec6753dbcc23450b713842df8f236d08666  ${root_dir}/rapidjson-1.0.2.tar.gz" | sha256sum -c -
+if [ $? -ne 0 ]; then
+    echo "Download of ${root_dir}/rapidjson-1.0.2.tar.gz failed or file is corrupted!" >& 2
     exit 1
 fi
 
 if [ ! -e ${root_dir}/msgpack-c-cpp-2.0.0.zip ]; then
-    echo "MsgPack cpp 2.0.0 zip file (${root_dir}/cpp-2.0.0.zip) is missing" >& 2
-    echo "Download it from here: https://github.com/msgpack/msgpack-c/archive/cpp-2.0.0.zip" >& 2
+    echo "MsgPack cpp 2.0.0 zip file (${root_dir}/cpp-2.0.0.zip) is missing. Downloading..." >& 2
+    wget -O ${root_dir}/msgpack-c-cpp-2.0.0.zip https://github.com/msgpack/msgpack-c/archive/cpp-2.0.0.zip >& 2
+fi
+
+echo "9f3860bc014355dbdf6519ffb78d54d120bb8d134dcb4eba35eb5103c1ac3cd1  ${root_dir}/msgpack-c-cpp-2.0.0.zip" | sha256sum -c -
+if [ $? -ne 0 ]; then
+    echo "Download of ${root_dir}/msgpack-c-cpp-2.0.0.zip failed or file is corrupted!" >& 2
     exit 1
 fi
+
 
 number_of_bits() {
     # Always favor 64-bit if we get something unanticipated
